Fix item with subitems crash when clicked
retejs/context-menu-plugin pull request #83
Opened 2024-02-25 22:55 UTC by Claybarn

Add dummy handler to item with subitems to prevent crashing. Fixes #81.

2024-02-27 01:03 UTC, Claybarn commented
This solved the crashing issue but introduced a new one. It prevented zooming in and out on the graph. Will see if there is another solution.

2024-02-28 18:46 UTC, Claybarn commented
Actually I take that back, the zooming issue happens if I compile the module from scratch without any changes at all.

2024-02-29 18:31 UTC, Ni55aN requested changes

2024-02-29 18:31 UTC, Ni55aN commented on src/presets/classic/factory.ts
> +    handler: Function()
this is unsafe due to Content Security Policy directive: "script-src"

2024-02-29 18:33 UTC, Ni55aN commented
>  the zooming issue happens if I compile the module from scratch

https://github.com/retejs/react-plugin/blob/main/src/presets/context-menu/components/Menu.tsx#L39

this is expected behavior. Do you think it should passthrough context menu?

2024-02-29 18:36 UTC, Ni55aN commented on src/presets/classic/factory.ts
> +    handler: Function()
also, can you squash commits into a single one with name of the format "fix: <your message>"? (unfortunately this part is not covered in the Contribution guide)

2024-03-03 22:19 UTC, Claybarn commented
I collapsed the commits, let me know if anything else needs changing.

2024-03-06 18:28 UTC, Ni55aN commented
please check CI and Commit linter workflows

2024-03-07 19:32 UTC, Ni55aN commented
commit message isn't conventional

2024-03-07 19:34 UTC, Ni55aN commented
anyway, I can merge it into different branch and rebase

2024-03-07 19:35 UTC, Ni55aN approved these changes

2024-03-07 19:50 UTC, merged